name: Del A TestFilght Link

on:
  workflow_dispatch:
    inputs:
      testflight_link:
        description: 'Testflight 公共测试的完整链接'
        required: true
      table:
        description: '链接分类'
        required: true
        type: choice
        options:
          - macos
          - ios
          - ios_game
          - tvos
          - chinese

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'pluwen/awesome-testflight-link'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Delete TestFlight Link
        run: python scripts/del_link.py "${{ github.event.inputs.testflight_link }}" "${{ github.event.inputs.table }}"

      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Delete TestFlight link: ${{ github.event.inputs.testflight_link }}"
            git push
          else
            echo "No changes to commit"
          fi
