name: Delete A TestFlight Link

on:
  workflow_dispatch:
    inputs:
      testflight_link:
        description: 'TestFlight 公共测试的完整链接或链接 ID'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'pluwen/awesome-testflight-link'
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Set up Python with uv
        run: uv venv && uv sync --locked
      - name: Delete TestFlight Link
        run: uv run python scripts/del_link.py "${{ github.event.inputs.testflight_link }}"

      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Delete TestFlight link: ${{ github.event.inputs.testflight_link }}"
            git push
          else
            echo "No changes to commit"
          fi
