name: Update TestFilght Link Status

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      python_version:
        description: '指定 Python 版本 3.6+ （不建议修改）'
        required: false
        default: '3.8'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      python_version: ${{ github.event.inputs.python_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Check env
        run: if [ -z "$python_version" ]; then python_version='3.8'; fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
          architecture: x64
      - name: Init Python Env
        run: pip install -r scripts/requirements.txt
      - name: Update TestFilght Link Status
        run: python scripts/update_status.py

      - name: Git commit && push
        run: |
          git_diff=`git diff`
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          git config --global user.email "user@noreply.github.com"
          git config --global user.name "user"
          git add .
          git commit -m "Github Action Auto Updated - `date`"
          git push
