name: Update TestFilght Link Status

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'pluwen/awesome-testflight-link'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Update TestFlight Link Status
        run: python scripts/update_status.py

      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Auto-update TestFlight link status: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi

  forked-repo:
    runs-on: ubuntu-latest
    if: github.repository != 'pluwen/awesome-testflight-link'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add upstream https://github.com/pluwen/awesome-testflight-link.git 
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main

